on:
  push:
    branches: main

jobs:
  refresh-html-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::htmltools 
            
      - name: Generate HTML by running R script
        run: Rscript -e 'source("make_html.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Refreshed HTML for pages' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
      
      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
  
          # Switch to the gh-pages branch or create it
          git fetch origin main || true
          git branch -d gh-pages || true
          git switch gh-pages || git switch --create gh-pages
  
          # Commit and push changes
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin
        
      
      
      